Feature: Openable after including .feature.cs as generated file
	In this case, we manually added the generated .feature.cs file to the .csproj file as if it is an autogenerated file, like it was
	before SpecFlow 3 with the SpecFlowSingleFileGenerator. 

Scenario: Openable after including .feature.cs as generated file
	Given I have entered 50 into the calculator
	And I have entered 70 into the calculator
	When I press add
	Then the result should be 120 on the screen